Web/Controllers/TiposExameController.cs
using System.Web.Mvc;
using ApplicationCore.Dto;
using ApplicationCore.Interfaces;

namespace Web.Controllers
{
    public class TiposExameController : Controller
    {
        private readonly ITiposExameService _tiposExameService;

        public TiposExameController(ITiposExameService tiposExameService)
        {
            _tiposExameService = tiposExameService;
        }

        public ActionResult Index()
        {
            var tiposExame = _tiposExameService.ListarTiposExame();
            return View(tiposExame);
        }
        
        
        public ActionResult Criar()
        {
            return View("Manter");
        }
        
        [HttpPost]
        public ActionResult Criar(TipoExameDto novoTipoExame)
        {
            if (!ModelState.IsValid)
            {
                return View("Manter", novoTipoExame);
            }

            try
            {
                _tiposExameService.ManterTipoExame(novoTipoExame);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Manter", novoTipoExame);
            }
        }
        
        public ActionResult Editar(int id)
        {
            var tipoExame = _tiposExameService.BuscarTipoExame(id);

            return View("Manter", tipoExame);
        }
        
        [HttpPost]
        public ActionResult Editar(TipoExameDto tipoExameEditado)
        {

            if (!ModelState.IsValid)
            {
                return View("Manter", tipoExameEditado);
            }

            try
            {
                _tiposExameService.ManterTipoExame(tipoExameEditado);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Manter", tipoExameEditado);
            }
        }
        
        public ActionResult Excluir(int id)
        {
            try
            {
                _tiposExameService.ExcluirTipoExame(id);
            }
            catch
            {
                ViewBag.Error = "Falha ao excluir registro";
            }
            
            return RedirectToAction("Index");
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Desafio Intelectah</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/datetimepicker/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
</head>
<body>
    <nav class="customNavbar navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            <span class="siteIcon"></span>
            @Html.ActionLink("Consultas", "Index", "Consultas", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar a navegação" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Exames", "Index", "Exames", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Tipos de Exames", "Index", "TiposExame", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Pacientes", "Index", "Pacientes", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Desafio Intelectah</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/inputmask")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)

</body>
</html>